name: .NET

on:
  push:
    branches: [ net5.0 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore DamaNoJornal.sln
    - name: Build
      run: dotnet build DamaNoJornal.sln --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish src/Web/DamaWeb/DamaWeb.csproj --runtime linux-x64 --self-contained false --configuration Release --output '/publish'
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'DamaWeb.zip'
        path: /publish
    - uses: actions/upload-artifact@v2
      with:
        name: drop
        path: 'DamaWeb.zip'
