name: .NET

on:
  push:
    branches: [ net5.0 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore DamaNoJornal.sln
    - name: Build
      run: dotnet build DamaNoJornal.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test tests/UnitTests/UnitTests.csproj --verbosity normal
    - name: Publish
      run: dotnet publish src/Web/DamaWeb/DamaWeb.csproj --runtime linux-x64 --configuration Release --output 'DamaWeb' --no-self-contained
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'DamaWeb.zip'
        path: DamaWeb
    - uses: actions/upload-artifact@v2
      with:
        name: drop
        path: 'DamaWeb.zip'
  
  deploy:
    needs: build
    runs-on: self-hosted    
    
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.9
      with:
        # Artifact name
        name: drop
        # Destination path
        path: /home/azureuser/deploy/
    - name: Deploy DamaShop
      run: /home/azureuser/deploy/shopDeploy.sh
  
